# Generated by Django 3.1 on 2020-08-24 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_program', models.CharField(max_length=100)),
                ('biaya', models.DecimalField(decimal_places=2, max_digits=15)),
                ('keterangan', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_trainer', models.CharField(max_length=100)),
                ('kelamin', models.CharField(choices=[('Pria', 'Pria'), ('Wanita', 'Wanita')], max_length=50)),
                ('tempat_lahir', models.CharField(blank=True, max_length=50, null=True)),
                ('tgl_lahir', models.DateField(blank=True, null=True)),
                ('nomor_handphone', models.CharField(max_length=12, unique=True)),
                ('agama', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=59)),
                ('sosmed', models.CharField(blank=True, max_length=50, null=True)),
                ('pendidikan_terakhir', models.CharField(blank=True, max_length=50, null=True)),
                ('alamat', models.CharField(blank=True, max_length=50, null=True)),
                ('is_trainer', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Form Trainer',
                'verbose_name_plural': 'Data Trainer',
            },
        ),
        migrations.CreateModel(
            name='Peserta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_peserta', models.CharField(max_length=100)),
                ('kelamin', models.CharField(choices=[('Pria', 'Pria'), ('Wanita', 'Wanita')], max_length=50)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tgl_lahir', models.DateField(blank=True, null=True)),
                ('nomor_handphone', models.CharField(max_length=12, unique=True)),
                ('agama', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('sosmed', models.CharField(blank=True, max_length=100, null=True)),
                ('pendidikan_terakhir', models.CharField(blank=True, max_length=100, null=True)),
                ('alamat', models.CharField(max_length=100)),
                ('alasan_kursus', models.CharField(max_length=100)),
                ('is_peserta', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Form Peserta',
                'verbose_name_plural': 'Data Peserta',
            },
        ),
        migrations.CreateModel(
            name='Pendaftaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_register', models.BooleanField(default=True)),
                ('keterangan', models.TextField(max_length=100)),
                ('peserta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.peserta')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.program')),
            ],
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelas', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('tgl_mulai', models.DateField(blank=True, null=True)),
                ('tgl_berakhir', models.DateField(blank=True, null=True)),
                ('keterangan', models.TextField(blank=True, max_length=100, null=True)),
                ('pendaftaran', models.ManyToManyField(to='app.Pendaftaran')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.program')),
                ('trainer', models.ManyToManyField(to='app.Trainer')),
            ],
        ),
    ]
