# Generated by Django 3.1 on 2020-09-03 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peserta',
            name='is_peserta',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='is_trainer',
        ),
    ]
