# Generated by Django 3.1 on 2020-09-04 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200903_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kelas',
            name='trainer',
        ),
        migrations.AddField(
            model_name='kelas',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.trainer'),
        ),
    ]
