# Generated by Django 3.1 on 2020-09-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200904_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kelas',
            name='trainer',
        ),
        migrations.AddField(
            model_name='kelas',
            name='trainer',
            field=models.ManyToManyField(to='app.Trainer'),
        ),
    ]
